on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Dependencies
        run: npm ci

      - name: Build for Chrome
        run: npm run build:chrome

      - name: Build for Firefox
        run: npm run build:firefox

      - name: Zip for Chrome
        if: startsWith(github.ref, 'refs/tags/')
        run: zip -q -r ../../home-assistant-chrome.zip *
        working-directory: dist/chrome

      - name: Zip for Firefox
        if: startsWith(github.ref, 'refs/tags/')
        run: zip -q -r ../../home-assistant-firefox.zip *
        working-directory: dist/firefox

      - name: Upload assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: home-assistant-*
          tag: ${{ github.ref }}
          file_glob: true
